config/routes.rb
MovieNinja::Application.routes.draw do

  root to: "users#index"
  resources :users, only: [:index, :create, :show]
  resource :sessions, only: [:create, :destroy]
  resources :surveys, only: [:new, :create]
  resources :votes, only: [:create]

  get 'surveys/:survey_url', to: 'surveys#show', as: :survey
  get 'preview_movie', to: 'movies#show'
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :title, :rotten_id, :imdb_id, :mob_poster_url, :det_poster_url, :rt_critics_score, :rt_audience_score, :mpaa_rating, :synopsis, :runtime, :release_date, :release_status

  validates :title, presence: :true

  fuzzily_searchable :title

  has_many :showtimes
  has_many :survey_movies
  has_many :surveys, through: :survey_movies
end

app/models/showtime.rb
class Showtime < ActiveRecord::Base
  attr_accessible :oc_title, :tms_id, :mpaa_rating, :release_year, :theater_name, :theater_id, :theater_showtime

  belongs_to :movie

  fuzzily_searchable :oc_title

  validates :oc_title, presence: :true
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :user_id, :survey_url, :info, :first_available_datetime, :last_available_datetime, :location_info, :zipcode, :movie

  belongs_to :user
  has_many :survey_movies
  has_many :movies, through: :survey_movies
  has_many :votes, through: :survey_movies

  before_save :generate_survey_url

  def generate_survey_url
    self.url = SecureRandom.urlsafe_base64
  end
end

app/models/survey_movie.rb
class SurveyMovie < ActiveRecord::Base
  has_many :votes
  belongs_to :survey
  belongs_to :movie

end

app/models/trigram.rb
class Trigram < ActiveRecord::Base
  attr_accessible :score, :trigram, :owner_type
  include Fuzzily::Model
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :surveys

  attr_accessible :email, :password

  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }

  def is_creator_of?(object)
    return true if object.respond_to? :user_id && object.user_id == self.id
    false
  end

  def has_surveys?
    self.surveys.any?
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :name

  belongs_to :survey_movie
  validates :name, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  end

  def show
    @movie = Movie.find(params[:movie_id])
    render :json => render_to_string(:partial => 'movie-preview', locals: {movie: @movie }).to_json
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  include SessionHelper

  def create
    @user = User.find_by_email(params[:user][:email])

    if login(@user)
      redirect_to new_survey_path
    else
      redirect_to root_path, flash: { error: 'Email or Password is Invalid' }
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  include SessionHelper

  before_filter :enforce_login, except: [:show]

  def new
    @survey = Survey.new
    @movies = Movie.where(release_status: 'wide').sample(21)
    @user = current_user
  end

  def create
    @survey = current_user.surveys.new
    @survey.info = params[:survey][:info]
    @survey.movie_ids = params[:survey][:movie_ids]
    @survey.first_available_datetime = params[:survey][:first_available_datetime]
    if @survey.save
      redirect_to survey_path(@survey.url)
    else
      flash[:error] = "Error creating survey"
      redirect_to root_path
    end
  end

  def show
    @survey = Survey.find_by_url(params[:survey_url])
    if @survey
      @movie_list = @survey.movies
      @survey_id = @survey.id
      if current_user == @survey.user
        @votes = {}
        @survey.survey_movies.each do |sm|
          @votes[sm.movie_id] = sm.votes.length
        end
        @vote_names = {}
        @survey.survey_movies.each do |sm|
          @vote_names[sm.movie_id] = sm.votes.map { |vote| vote.name }
        end
        render :survey_confirmation
      else
        @user = User.new
        render 'survey_visitor'
      end
    else
      flash[:error] = "No survey at that URL"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include SessionHelper

  def index
    @movies_sample = Movie.where(release_status: 'wide').sample(8)

    @user = current_user || User.new
    if current_user
      redirect_to new_survey_path
    end
  end

  def create
    @user = User.new
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]

    if @user.save
      session[:current_user_id] = @user.id
      redirect_to new_survey_path
    else
      redirect_to root_path, flash: { error: @user.errors.full_messages.to_sentence }
    end
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @user = User.new

    @vote = Vote.new
    @survey_movie = SurveyMovie.where(survey_id: params[:survey_id], movie_id: params[:movie_id_voted_on]).first

    @vote.name = params[:voter_name]
    @vote.survey_movie_id = @survey_movie.id
    @movie = @vote.survey_movie.movie

    if @vote.save
      render 'confirmation'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def login(user)
    if user && user.authenticate(params[:user][:password])
      session[:current_user_id] = @user.id
    end
  end

  def logout
    session.clear
    @user = nil
  end

  def current_user
    @user ||= User.find(session[:current_user_id]) if signed_in?
  end

  def signed_in?
    session[:current_user_id] ? true : false
  end

  def enforce_login
    if !signed_in?
      redirect_to root_path
      flash[:error] = "You must be logged in to access that page."
    end
  end
end

app/helpers/survey_helper.rb
module SurveyHelper
  require 'securerandom'
end

app/helpers/twilio_helper.rb
twilio_helper.rb

app/views/layouts/_modal.html.erb
<div class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal">
  <%= image_tag "ninja.svg", { id: 'logo'}%>
  <%= link_to "Movie Ninja", root_path, class: "pure-menu-heading", id: "heading" %>
  <ul>
    <% if signed_in? %>
      <li><%= @user.email %></li>
      <li><a href="#myModal-user-surveys" data-toggle="modal" id="my-surveys-link"><%= image_tag "my_surveys.svg",{id: 'my-surveys-button'} %></a></li>
      <% if request.fullpath == new_survey_path %>
        <li><a href="#" id="toggle-sidebar-link"><i class="fa fa-bars" id="toggle-sidebar-button"></i></a></li>
      <% end %>
      <li><%= button_to "Logout", sessions_path, class: 'pure-button', id: 'logout-button', method: :delete %></li>
    <% else %>
      <li><button class="pure-button" data-toggle="modal" href="#myModal-signin" id="login-button">Login</button></li>
    <% end %>
  </ul>
</div>

<div id="myModal-user-surveys" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <h2 id="myModalLabel">My Current Surveys</h2>
  </div>

   <div id="user-surveys">
    <% if signed_in? && current_user.has_surveys? %>
      <ul>
        <% Survey.where(user_id: session[:current_user_id]).each do |survey| %>
          <li><b>Movie date on:</b> <%= survey.first_available_datetime.strftime("%b %d, %Y") %></li>
          <li><b>Movies:</b> <%= survey.movies.map{ |movie| movie.title}.join(', ') %></li>
          <li><a href=<%= survey_path(survey.url) %>>Link to Survey</a></li>
        </br>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="modal-footer">
    <button class="pure-button" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

<% unless signed_in? %>
  <div id="myModal-signin" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
       <h2 id="myModalLabel"> <span id="modallogo"><%=image_tag "ninja.svg"%></span>Sign In / Sign Up</h2>
    </div>

    <div class="modal-body pure-g">
      <div class="pure-u-1-2">
        <%= render partial: "layouts/signup", locals: {user: @user} %>
      </div>
      <div class="pure-u-1-2">
        <%= render partial: "layouts/signin", locals: {user: @user} %>
      </div>
    </div>

    <div class="modal-footer">
      <button class="pure-button" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal">
  <%= image_tag "ninja.svg", { id: 'logo'}%>
  <%= link_to "Movie Ninja", root_path, class: "pure-menu-heading", id: "heading" %>
  <ul>
    <% if signed_in? %>
      <li><%= @user.email %></li>
      <li><a href="#myModal-user-surveys" data-toggle="modal" id="my-surveys-link"><%= image_tag "my_surveys.svg",{id: 'my-surveys-button'} %></a></li>
      <% if request.fullpath == new_survey_path %>
        <li><a href="#" id="toggle-sidebar-link"><i class="fa fa-bars" id="toggle-sidebar-button"></i></a></li>
      <% end %>
      <li><%= button_to "Logout", sessions_path, class: 'pure-button', id: 'logout-button', method: :delete %></li>
    <% else %>
      <li><button class="pure-button" data-toggle="modal" href="#myModal-signin" id="login-button">Login</button></li>
    <% end %>
  </ul>
</div>

<div id="myModal-user-surveys" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <h2 id="myModalLabel">My Current Surveys</h2>
  </div>

   <div id="user-surveys">
    <% if signed_in? && current_user.has_surveys? %>
      <ul>
        <% Survey.where(user_id: session[:current_user_id]).each do |survey| %>
          <li><b>Movie date on:</b> <%= survey.first_available_datetime.strftime("%b %d, %Y") %></li>
          <li><b>Movies:</b> <%= survey.movies.map{ |movie| movie.title}.join(', ') %></li>
          <li><a href=<%= survey_path(survey.url) %>>Link to Survey</a></li>
        </br>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="modal-footer">
    <button class="pure-button" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

<% unless signed_in? %>
  <div id="myModal-signin" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
       <h2 id="myModalLabel"> <span id="modallogo"><%=image_tag "ninja.svg"%></span>Sign In / Sign Up</h2>
    </div>

    <div class="modal-body pure-g">
      <div class="pure-u-1-2">
        <%= render partial: "layouts/signup", locals: {user: @user} %>
      </div>
      <div class="pure-u-1-2">
        <%= render partial: "layouts/signin", locals: {user: @user} %>
      </div>
    </div>

    <div class="modal-footer">
      <button class="pure-button" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
  </div>
<% end %>

app/views/layouts/_signin.html.erb
<p>Sign in:</p>
<%= simple_form_for @user, url: sessions_path, html: {id: 'form-sign-in-user', class: 'form-sign-in pure-form pure-form-stacked'} do |f| %>
  <%= f.input :email, label: false, placeholder: 'email', input_html: { size: 20, id: 'form-sign-in-email' } %>
  <%= f.input :password, label: false, required: true, placeholder: 'password', input_html: { size: 20, id: 'form-sign-in-password' } %>
  <%= f.submit "sign in", class: "pure-button pure-button-primary" %>
<% end %>

app/views/layouts/_signup.html.erb
<p>Register:</p>
<%= simple_form_for @user, html: {id: 'form-register-user' , class: "form-register pure-form pure-form-stacked" } do |f| %>
  <%= f.input :email, label: false, placeholder: 'email', input_html: { size: 20, id: 'form-sign-up-email' } %>
  <%= f.input :password, label: false, required: true, placeholder: 'password', input_html: { size: 20, id: 'form-sign-up-password' }, error_html: { id: 'password_error'} %>
  <%= f.input :password_confirmation, label: false, required: true, placeholder: 'password again', input_html: { size: 20, id: 'form-sign-up-password-confirm' } %>
  <%= f.submit "sign-up", class: "pure-button pure-button-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieNinja</title>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= csrf_meta_tags %>
  <script src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
</head>

<body>
 <nav>
   <%= render partial: "layouts/navbar" %>
 </nav>
  <% if flash[:error] %>
      <div class='error'><%= flash[:error] %></div>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/movies/_movie-preview.html.erb
<h3 class="movie-preview-title">
  <%= @movie.title %>
</h3>

<ul class="movie-preview-info">
  <li class="movie-preview-mpaa-rating">(<%= @movie.mpaa_rating %>)</li>
  <li class="movie-preview-runtime"><%= @movie.runtime %> minutes</li>
</ul>

<ul class="movie-preview-scores">
  <li>Critics: <%= @movie.rt_critics_score %>%</li>
  <li>Audience: <%= @movie.rt_audience_score %>%</li>
</ul>

<p class="movie-preview-synopsis">
  <%= @movie.synopsis  %>
</p>

app/views/movies/_movie-votes-count.html.erb
<div class = "movie-box" data-id=<%=movie.id%>>
  <div class = "movie-box-poster">
    <%= image_tag(movie.det_poster_url) %>
  </div>
  <div class = "movie-box-title">
    <%= movie.title %>
  </div>
  <div class = "movie-votes">
    <strong>Votes: <%= @votes[movie.id] %></strong>
  </div>
  <ul class = "movie-votes-names">
    <% @vote_names[movie.id].each do |voter| %>
      <li><%=  voter %></li>
    <% end %>
  </ul>
  <div class = "movie-box-critics-score collapsed">
    Tomato Score: <%= movie.rt_critics_score %>
  </div>
  <div class = "movie-box-mpaa-rating collapsed">
    <%= movie.mpaa_rating %>
  </div>
</div>

app/views/movies/_movie-votes.html.erb
<div class = "movie-box" data-id=<%=movie.id%>>
  <div class = "movie-box-poster">
    <%= link_to( image_tag(movie.det_poster_url), "#", data: { id: movie.id } ) %>
  </div>
  <div class = "movie-box-title">
    <%= movie.title %>
  </div>
  <div class = "movie-votes">
    <strong>Votes: <%= @votes[movie.id] %></strong>
  </div>
</div>

app/views/movies/_movie-voting.html.erb
<div class = "movie-box" data-id=<%=movie.id%>>
  <div class = "movie-box-poster">
    <%= link_to( image_tag(movie.det_poster_url), "#", data: { id: movie.id } ) %>
  </div>
  <div class = "movie-box-title">
    <%= movie.title %>
  </div>
  <div class = "movie-box-critics-score collapsed">
    Tomato Score: <%= movie.rt_critics_score %>
  </div>
  <div class = "movie-box-mpaa-rating collapsed">
    <%= movie.mpaa_rating %>
  </div>
</div>

app/views/movies/_movie.html.erb
<div class = "movie-box" data-id=<%=movie.id%>>
  <div class = "movie-box-poster">
    <%= link_to( image_tag(movie.det_poster_url), "#", data: { id: movie.id } ) %>
  </div>
  <div class = "movie-box-title">
    <%= movie.title %>
    <a href="#"><span class="enqueue-movie-button" data-id=<%=movie.id%>><i class="fa fa-plus-square"></i></span></a>
  </div>

  <ul class = "movie-box-info collapsed">
    <li><%= movie.runtime %> minutes</li>
    <li>(<%= movie.mpaa_rating %>)</li>
  </ul>

  <ul class = "movie-box-scores collapsed">
    <li>Critics: <%= movie.rt_critics_score %>%</li>
    <li>Audience: <%= movie.rt_audience_score %>%</li>
  </ul>
</div>

app/views/surveys/new.html.erb
<div class="movie-list">
  <h3 class = "movie-survey-header">Select movies to add to your survey</h3>
  <%= render @movies %>
</div>

<div id="movie-preview-container">
  <div id="starting-instructions">
    <p>Click the <i class="fa fa-plus-square"></i>button next to the title to add a movie to your survey.</p>
    <p>Click the movie poster to see additional details in this panel.</p>
    <p>Use the <i class="fa fa-bars"></i>button in the nav bar to get a list of movies currently in your survey. You'll also have a chance to trim your final list and add a comment before sending it out to your friends.</p>
  </div>
</div>

<div id="sidebar" class="hidden">
  <div id="sidebar-content">
    <h3 id="sidebar-heading">Your Picks...</h3>
    <div id="selected-movies">
    </div>
    <%= form_for @survey do |f| %>
      <textarea id="survey-comment" name="survey[info]" placeholder="Anything else you want your friends to know..." required></textarea>
      <input type="date" name="survey[first_available_datetime]" id="datepicker" required>
      <input type="submit" class="pure-button pure-button-small" id='submit-survey'>
    <% end %>
  </div>
</div>

app/views/surveys/show.html.erb
<div class = "movie-list">
  <%= render partial: :movie, collection: @movie_list, as: :movie %>
</div>

app/views/surveys/survey_confirmation.html.erb
<div class = "survey-confirmation-info">
  <h2>Here's your survey!</h2>
  <p class = "survey-info"><%= @survey.info %></p>
  <h3>Visitors will be asked to vote on the below movies.</h3>
  <p>Happening on <%= @survey.first_available_datetime.strftime("%b %d, %Y") %></p>
  <h3>Send this survey link to your friends:</h3>
  <%= link_to survey_url(@survey.url) %>
</div>
<% if @movie_list.any? %>
  <div class = "movie-list-confirmation">
    <%= render partial: 'movies/movie-votes-count', collection: @movie_list, as: :movie %>
  </div>
<% end %>

app/views/surveys/survey_visitor.html.erb
<div class = "survey-confirmation-info">
  <h2>Survey created by: <%=@survey.user.email %></h2>
  <h3>Information:</h3>
  <p class = "survey-info"><%= @survey.info %></p>
  <p>Plan to go on: <%= @survey.first_available_datetime.strftime("%b %d, %Y") %></p>
</div>

<div class = "movie-list-confirmation">
  <%= render partial: 'movies/movie-voting', collection: @movie_list, as: :movie %>
</div>

<form id="vote-form" method='post' action=<%= votes_path %>>
  <legend> Your Ninja Vote! </legend>
  <ul>
    <% @movie_list.each do |movie| %>
      <li><input type="radio" name="movie_id_voted_on" value=<%= movie.id %> ><span>  <%= movie.title %></span></li>
      <input type="hidden" name="survey_id" value=<%= @survey.id %> >
    <% end %>
  </ul>
  <input type="textfield" id="voter_name_field" name="voter_name" placeholder="Your Name" required>
  <input type="submit" value="Vote">
</form>

app/views/users/index.html.erb
<div id="page-welcome">
  <h1>Welcome to Movie Ninja</h1>
  <p>The place to schedule movies with your friends! <br>
    <p><a href="#myModal-signin" data-toggle="modal">Login</a> to plan your next movie-outing.</p>
</div>

<div class = "movies-sample-list">
  <% @movies_sample.each do |movie| %>
    <div class = "movie-box-on-home" data-id=<%=movie.id%>>
      <div class = "movie-box-poster">
        <%= image_tag(movie.det_poster_url) %>
      </div>
      <div class = "movie-box-title">
        <%= movie.title %>
      </div>
      <div class = "movie-box-critics-score collapsed">
        Tomato Score: <%= movie.rt_critics_score %>
      </div>
      <div class = "movie-box-mpaa-rating collapsed">
        <%= movie.mpaa_rating %>
      </div>
    </div>
  <% end %>
</div>

app/views/votes/confirmation.html.erb
<div class = "survey-confirmation-info">
  <h1>Thanks for voting!</h1>
  <p>You voted for:</p>
  <div class = "movie-box" data-id=<%=@movie.id%>>
    <div class = "movie-box-poster">
      <%= image_tag(@movie.det_poster_url) %>
    </div>
    <div class = "movie-box-title">
      <%= @movie.title %>
    </div>
    <div class = "movie-box-critics-score collapsed">
      Tomato Score: <%= @movie.rt_critics_score %>
    </div>
    <div class = "movie-box-mpaa-rating collapsed">
      <%= @movie.mpaa_rating %>
    </div>
  </div>
</div>